name: Beta Build

on: 
  push:
      - $default-branch

  workflow_dispatch: 
    inputs: 
      branch:
        description: 'Branch to build'
        required: true 
        type: string

jobs:
  call-workflow:
    uses: PepperDash/workflow-templates/.github/workflows/essentialsplugins-betabuilds.yml@main
    secrets: inherit
    with: 
      branch: ${{ inputs.branch }}
      defualt-branch: ${{ default-branch }}


